---
- name: Create /opt/src
  file: path=/opt/src state=directory recurse=yes

- name: Create lib dir
  file: path={{sbt_lib_path_target}} state=directory recurse=yes

- name: Download sbt v{{sbt_version}}
  get_url: url={{sbt_download_url}} 
    dest=/opt/src/{{sbt_archive_file}}

- name: Unpack sbt
  unarchive: src=/opt/src/{{sbt_archive_file}} dest={{sbt_lib_path_target}} copy=no

- name: Link sbt
  file: state=link src={{sbt_lib_path_target}}/sbt/bin/sbt dest={{sbt_link_target}}
